version: "3"
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis-service
    environment:
      - REDIS_HOST=redis-service

  redis-service:
    image: "redis:latest"
    ports:
      - "6379:6379"
