apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "giropops-senhas.name" . }}
  name: {{ template "giropops-senhas.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "giropops-senhas.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "giropops-senhas.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
          ports:
            - name: http
              containerPort: {{ .Values.service.ports[0].targetPort }}
