apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "giropops-senhas.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.secretName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "giropops-senhas.name" . }}
            port:
              number: {{ .Values.containerPort }}
