apiVersion: v1
kind: Service
metadata:
  name: {{ template "giropops-senhas.name" . }}
  labels:
    app: {{ template "giropops-senhas.name" . }}
spec:
  selector:
    app: {{ template "giropops-senhas.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      name: {{ .Values.service.name }}
  type: {{ .Values.service.type }}
